"""empty message

Revision ID: 5968e79f6829
Revises: 8c52d69fde91
Create Date: 2021-11-07 16:51:37.800053

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5968e79f6829'
down_revision = '8c52d69fde91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
