"""empty message

Revision ID: 8c52d69fde91
Revises: 
Create Date: 2021-11-07 16:15:08.162416

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8c52d69fde91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
